"use client";
import { FileDown, Loader2 } from "lucide-react";
import { useState } from "react";
import { useApp } from "@/lib/store";

/**
 * Capture the entire dashboard as a multi-page PDF clinical report.
 * Uses dynamic imports so jsPDF + html2canvas don't bloat the initial bundle.
 */
export function ReportExport() {
  const { sim, design, prediction, opt, heteroplasmy, selectedRegion } = useApp();
  const [busy, setBusy] = useState(false);

  async function generate() {
    setBusy(true);
    try {
      const [{ default: jsPDF }, { toCanvas }] = await Promise.all([
        import("jspdf"),
        import("html-to-image"),
      ]);

      const root = document.getElementById("report-root") ?? document.body;
      const canvas = await toCanvas(root, {
        backgroundColor: "#02030a",
        pixelRatio: 1.5,
        cacheBust: true,
        // Skip nodes html-to-image can't serialize (3D canvases sometimes choke)
        filter: (node) => {
          if (!(node instanceof HTMLElement)) return true;
          return !node.classList?.contains("no-export");
        },
      });

      const pdf = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
      const pageW = pdf.internal.pageSize.getWidth();
      const pageH = pdf.internal.pageSize.getHeight();
      const margin = 28;

      // Cover header
      pdf.setFillColor(2, 3, 10);
      pdf.rect(0, 0, pageW, pageH, "F");
      pdf.setTextColor(165, 243, 252);
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(26);
      pdf.text("Revitalize AI", margin, 60);
      pdf.setFontSize(12);
      pdf.setTextColor(147, 160, 201);
      pdf.text("Clinical Simulation Report", margin, 80);

      pdf.setFontSize(10);
      pdf.setTextColor(232, 237, 255);
      let y = 120;
      const line = (label: string, val: string) => {
        pdf.setTextColor(147, 160, 201);
        pdf.text(label, margin, y);
        pdf.setTextColor(232, 237, 255);
        pdf.text(val, margin + 170, y);
        y += 18;
      };

      line("Generated", new Date().toISOString());
      line("Target locus", selectedRegion ?? "—");
      if (design) {
        line("Spacer (gRNA)", design.spacer);
        line("PAM", design.pam);
        line("pegRNA 3′ ext.", design.pegrna_3p);
        line("Edit position", `m.${design.edit_position}`);
      }
      if (prediction) {
        line("Predicted on-target", `${(prediction.on_target * 100).toFixed(1)}%`);
        line("Predicted off-target", `${(prediction.off_target_risk * 100).toFixed(1)}%`);
        line("Spacer GC", `${(prediction.gc_content * 100).toFixed(0)}%`);
        line("PBS Tm", `${prediction.pbs_tm.toFixed(0)} °C`);
      }
      line("Initial heteroplasmy", `${(heteroplasmy * 100).toFixed(0)}%`);
      if (sim) {
        line("Sim duration", `${sim.t.at(-1)?.toFixed(0)} h`);
        line("Final pathogenic load", `${(sim.final_pathogenic * 100).toFixed(1)}%`);
        line("Final edited fraction", `${(sim.final_edited * 100).toFixed(1)}%`);
        line(
          "60% rescue time",
          sim.therapeutic_threshold_h != null ? `${sim.therapeutic_threshold_h.toFixed(1)} h` : "not reached",
        );
      }
      if (opt) {
        y += 8;
        pdf.setTextColor(94, 234, 212);
        pdf.setFont("helvetica", "bold");
        pdf.text("Optimized dosing schedule (Optuna TPE)", margin, y);
        y += 16;
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(232, 237, 255);
        for (const d of opt.best_doses) {
          pdf.text(`  • t = ${d.time.toFixed(1)} h    bolus = ${d.amount.toFixed(2)}`, margin, y);
          y += 14;
        }
      }

      // Dashboard screenshot — multi-page
      pdf.addPage();
      pdf.setFillColor(2, 3, 10);
      pdf.rect(0, 0, pageW, pageH, "F");

      const imgData = canvas.toDataURL("image/jpeg", 0.85);
      const imgW = pageW - margin * 2;
      const imgH = (canvas.height * imgW) / canvas.width;
      // Split into pages
      let remaining = imgH;
      let yOffset = 0;
      while (remaining > 0) {
        const sliceH = Math.min(pageH - margin * 2, remaining);
        pdf.addImage(
          imgData,
          "JPEG",
          margin,
          margin - yOffset,
          imgW,
          imgH,
          undefined,
          "FAST",
        );
        remaining -= sliceH;
        yOffset += sliceH;
        if (remaining > 0) {
          pdf.addPage();
          pdf.setFillColor(2, 3, 10);
          pdf.rect(0, 0, pageW, pageH, "F");
        }
      }

      // Footer page
      pdf.addPage();
      pdf.setFillColor(2, 3, 10);
      pdf.rect(0, 0, pageW, pageH, "F");
      pdf.setTextColor(147, 160, 201);
      pdf.setFontSize(10);
      pdf.text(
        [
          "Revitalize AI — Caltech Hackathon",
          "",
          "This report was generated by an AI-driven simulation platform for doxycycline-",
          "inducible CRISPR prime editing of mitochondrial DNA via the PNPase RNA-import",
          "pathway. Results are computational predictions calibrated to published models",
          "of mtDNA heteroplasmy dynamics, prime-editor efficiency, and pharmacokinetics,",
          "and should not be construed as clinical advice.",
          "",
          "Backend: FastAPI · PyTorch · SciPy ODE · Optuna · Anthropic Claude Opus 4.7",
          "Frontend: Next.js · TypeScript · Tailwind · react-three-fiber · Recharts",
        ].join("\n"),
        margin,
        80,
      );

      pdf.save(`revitalize-report-${(selectedRegion ?? "run").replace(/\W+/g, "_")}.pdf`);
    } finally {
      setBusy(false);
    }
  }

  return (
    <button className="btn" onClick={generate} disabled={busy || !sim}>
      {busy ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4" />}
      {busy ? "Rendering PDF…" : "Export Clinical Report (PDF)"}
    </button>
  );
}
